name: 📝 I&A New Request Form
description: Submit a new analytics/data request from another team.
title: "[Request] <Add a short descriptive title here>"
labels: [request, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        👋 Thanks for submitting a request to the I&A team! Please fill in the details below to help us understand and prioritize your request.

  - type: input
    id: requestor
    attributes:
      label: Requestor Name & Team
      description: Who is making the request?
      placeholder: ex. John Doe (Product Team)
    validations:
      required: true

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of request is this?
      options:
        - New Dashboard
        - Dashboard Migration
        - Dashboard Enhancement
        - Dashboard for Searching/Investigative Use
        - Dashboard Debugging/Troubleshooting
        - New Metric/KPI Definition
        - One-Time Analysis or Report
        - Ad Hoc Data Extraction
        - Others (please specify in the description)
    validations:
      required: true


  - type: textarea
    id: request-details
    attributes:
      label: Request Description
      description: >
        What do you need help with? Please provide context, goals, and links to any relevant docs or dashboards.  
        👉 **If this is a dashboard migration request, please include screenshots of the key visuals or layout you'd like to preserve.**
      placeholder: ex. We need a dashboard to monitor QR Ph daily adoption by channel.
    validations:
      required: true

  - type: textarea
    id: reference-tables
    attributes:
      label: Reference Tables
      description: Please list any tables or views needed for this request.
      placeholder: ex. data_ops.data_gross_profit_calculation, data_merchants

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this request?
      options:
        - P0 - Critical (urgent or blocking)
        - P1 - High (needs to be done this sprint)
        - P2 - Medium/Low (can wait until next sprint or later)
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: What does "done" look like? How will we know this is successful?
      placeholder: ex. When the dashboard is live and being used to track adoption across merchants.

  - type: input
    id: due-date
    attributes:
      label: Preferred Due Date (if any)
      description: Optional — let us know if you have a deadline.
      placeholder: ex. May 25, 2025

  - type: textarea
    id: job-stories
    attributes:
      label: Job Stories (Optional)
      description: Optional — Share any job stories that provide context to this request (e.g., "As a user, I want to view the QR adoption trend to track merchant performance").
      placeholder: ex. "As a merchant, I want to filter transactions by payment method to focus on QR Ph metrics."
