name: 📝 Onboarding New Request Form
description: Submit a new onboarding request from another team.
title: "[Request] <Add a short descriptive title here>"
labels: [request, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        👋 Thanks for submitting a request to the Onboarding team! Please fill in the details below to help us understand and prioritize your request.

  - type: input
    id: requestor
    attributes:
      label: Requestor Name & Team
      description: Who is making the request?
      placeholder: ex. John Doe (Product Team)
    validations:
      required: true

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of request is this?
      options:
        - Activation Follow-up
        - Provider Onboarding Follow-up
        - Request Provider Onboarding Configuration
        - Change Card Configured
        - Payout on hold
        - Adding a website
        - Bank Account Change / Secretary Certificate submission
        - Generic Query
        - Refresh / Re-KYC Request
        - Declined or Dormant Account
        - Others (please specify in the description)
    validations:
      required: true


  - type: textarea
    id: request-details
    attributes:
      label: Request Description
      description: >
        What do you need help with? Please provide context, goals, and links to any relevant docs or dashboards.  
        👉 **If this is a dashboard migration request, please include screenshots of the key visuals or layout you'd like to preserve.**
      placeholder: ex. We need a dashboard to monitor QR Ph daily adoption by channel.
    validations:
      required: true

  - type: textarea
    id: reference-tables
    attributes:
      label: Reference Tables
      description: Please list any tables or views needed for this request.
      placeholder: ex. data_ops.data_gross_profit_calculation, data_merchants

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this request?
      options:
        - P0 - Critical
        - P1 - High 
        - P2 - Medium 
        - P3 - Low 
    validations:
      required: true

  - type: input
    id: due-date
    attributes:
      label: Preferred Due Date (if any)
      description: Optional — let us know if you have a deadline and reason for urgent ones.
      placeholder: ex. May 25, 2025 - merchant will go live in 1 week

  - type: textarea
    id: org ID
    attributes:
      label: Organization ID (Optional)
      description: Org ID — Please put an org ID in your request
      placeholder: ex. "org_XXX"
